FROM node:14
WORKDIR /app-node
# VARIAVEL
ARG PORT_BUILD=600
# VARIAVEL DE AMBIENTE
ENV PORT=${PORT_BUILD} 
# PORTA QUE SERA EXECUTADA
EXPOSE ${PORT_BUILD}
# HOST | IMAGEM (COM BASE NO WORKDIR)
COPY . .
RUN npm install
ENTRYPOINT npm start